# Generated by Django 6.0.5 on 2026-05-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('symbol', models.CharField(db_index=True, help_text='Maps to script_ticker', max_length=20, primary_key=True, serialize=False)),
                ('security_name', models.CharField(help_text='Maps to company_name', max_length=255)),
                ('sector_name', models.CharField(blank=True, help_text='Maps to sector', max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'nepse_company_profiles',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockPriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='The raw ID from the source API', unique=True)),
                ('business_date', models.DateField(db_index=True)),
                ('security_id', models.IntegerField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_price_adj', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price_adj', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price_adj', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price_adj', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment_factor', models.DecimalField(decimal_places=10, max_digits=14)),
                ('average_traded_price_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('company', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='core_analysis.companyprofile')),
            ],
            options={
                'db_table': 'nepse_todayprice_adj',
                'ordering': ['-business_date', 'company'],
                'unique_together': {('business_date', 'company')},
            },
        ),
    ]
