# Generated by Django 6.0.5 on 2026-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepseDailyStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text="Maps to JSON 'id'", unique=True)),
                ('business_date', models.DateField(db_index=True)),
                ('security_id', models.CharField(max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('security_name', models.CharField(max_length=255)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_traded_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_traded_quantity', models.BigIntegerField()),
                ('total_traded_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_trades', models.IntegerField()),
                ('market_capitalization', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fifty_two_week_high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fifty_two_week_low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_updated_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'nepse_daily_stock_prices',
                'ordering': ['-business_date', 'symbol'],
                'unique_together': {('business_date', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='NepseMarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text="Maps to JSON 'id'", unique=True)),
                ('business_date', models.DateField(db_index=True, help_text="Maps to JSON 'date'")),
                ('sector_name', models.CharField(db_index=True, help_text="Maps to JSON 'sector'", max_length=100)),
                ('open_index', models.DecimalField(decimal_places=2, help_text="Maps to JSON 'open'", max_digits=12)),
                ('high_index', models.DecimalField(decimal_places=2, help_text="Maps to JSON 'high'", max_digits=12)),
                ('low_index', models.DecimalField(decimal_places=2, help_text="Maps to JSON 'low'", max_digits=12)),
                ('close_index', models.DecimalField(decimal_places=2, help_text="Maps to JSON 'close'", max_digits=12)),
                ('absolute_change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_change', models.DecimalField(decimal_places=4, max_digits=6)),
                ('turnover_values', models.DecimalField(decimal_places=2, max_digits=18)),
                ('turnover_volume', models.BigIntegerField()),
                ('total_transaction', models.IntegerField()),
                ('number_52_weeks_high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_52_weeks_low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'nepse_market_indices',
                'ordering': ['-business_date', 'sector_name'],
                'unique_together': {('business_date', 'sector_name')},
            },
        ),
    ]
