# Generated by Django 6.0.5 on 2026-06-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0002_nepsedailystockprice_nepsemarketindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepseFloorsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.BigIntegerField(help_text="Maps to JSON 'id'", unique=True)),
                ('contract_no', models.CharField(db_index=True, help_text="Maps to JSON 'contract_no'", max_length=32)),
                ('business_date', models.DateField(db_index=True, help_text="Maps to JSON 'calculation_date'")),
                ('stock_symbol', models.CharField(db_index=True, max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer', models.IntegerField(db_index=True)),
                ('seller', models.IntegerField(db_index=True)),
                ('quantity', models.BigIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('trade_time', models.TimeField(blank=True, help_text="Maps to JSON 'time'", null=True)),
            ],
            options={
                'db_table': 'nepse_floorsheet',
                'ordering': ['-business_date', 'stock_symbol'],
                'indexes': [models.Index(fields=['business_date', 'stock_symbol'], name='nepse_floor_busines_eaa6a3_idx'), models.Index(fields=['business_date', 'buyer'], name='nepse_floor_busines_417eff_idx'), models.Index(fields=['business_date', 'seller'], name='nepse_floor_busines_2bc64f_idx')],
            },
        ),
    ]
