# Generated by Django 6.0.5 on 2026-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0004_floorsheet_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('broker_number', models.IntegerField(help_text='NEPSE broker code; matches floorsheet buyer/seller', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=20)),
                ('tms_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_dealer', models.BooleanField(default=False, help_text='True if the firm also operates as a NEPSE stock dealer')),
            ],
            options={
                'db_table': 'nepse_brokers',
                'ordering': ['broker_number'],
            },
        ),
    ]
