# Generated by Django 6.0.5 on 2026-06-26 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0005_broker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(db_index=True, max_length=100)),
                ('fiscal_year_ad', models.CharField(db_index=True, help_text="Gregorian fiscal year label, e.g. '2024/25'", max_length=10)),
                ('quarter', models.PositiveSmallIntegerField(db_index=True, help_text='0 = annual / 1–4 = quarter')),
                ('data_source', models.CharField(db_index=True, max_length=20)),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('fs_type', models.CharField(db_index=True, help_text='Statement type, e.g. BS / PL / CF', max_length=10)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(db_index=True, max_length=80)),
                ('sorting_code', models.CharField(db_index=True, max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField()),
                ('fiscal_year_bs', models.BigIntegerField(db_column='fiscal_year_bs_id', help_text='FK id -> nepali_datetime_fiscalyear.id (not modelled here)')),
                ('item', models.BigIntegerField(db_column='item_id', help_text='FK id -> fundamentals_accountdictionary.id (not modelled here)')),
            ],
            options={
                'db_table': 'fundamentals_financialstatdbs',
                'ordering': ['ticker', 'fiscal_year_ad', 'quarter', 'sorting_code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_portfolio',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_close', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ltp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core_analysis.portfolio')),
            ],
            options={
                'db_table': 'portfolio_holding',
                'ordering': ['symbol'],
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
    ]
