# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_approved(apps, schema_editor):
    AccountApproval = apps.get_model("core_analysis", "AccountApproval")
    AccountApproval.objects.filter(
        models.Q(reviewed_at__isnull=False) | models.Q(user__is_active=True)
    ).update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("core_analysis", "0007_emailactivation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailActivation",
            new_name="AccountApproval",
        ),
        migrations.RenameField(
            model_name="accountapproval",
            old_name="email",
            new_name="contact_email",
        ),
        migrations.RenameField(
            model_name="accountapproval",
            old_name="activated_at",
            new_name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="accountapproval",
            name="sent_at",
        ),
        migrations.AddField(
            model_name="accountapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="accountapproval",
            name="review_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="accountapproval",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_account_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accountapproval",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_approval",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="accountapproval",
            table="account_approval_request",
        ),
        migrations.AlterModelOptions(
            name="accountapproval",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RunPython(mark_existing_approved, migrations.RunPython.noop),
    ]
