# Generated by Django 6.0.5 on 2026-07-01 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0008_accountapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('wacc_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('modified', models.CharField(blank=True, default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core_analysis.portfolio')),
            ],
            options={
                'db_table': 'portfolio_holding_cost',
                'ordering': ['symbol'],
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
    ]
