# Generated by Django 6.0.5 on 2026-07-01 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0009_holdingcost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('referer', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_page_visit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'path'], name='site_page_v_created_70d389_idx')],
            },
        ),
    ]
