# Generated by Django 6.0.5 on 2026-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0012_broker_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginEligibleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Trading symbol / ticker, e.g. NABIL (the natural key).', max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('sector', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('is_eligible', models.BooleanField(db_index=True, default=True, help_text='Untick to de-list without losing the record.')),
                ('margin_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Max loan-to-value the broker lends against this scrip, in %% (e.g. 50.00).', max_digits=6, null=True)),
                ('risk_category', models.CharField(blank=True, default='', help_text="Optional risk group / class from the source list (e.g. 'Group A').", max_length=50)),
                ('source', models.CharField(blank=True, default='', help_text='Where this entry came from (regulator circular, broker sheet, upload…).', max_length=100)),
                ('effective_date', models.DateField(blank=True, help_text='Date this eligibility takes effect, if the source states one.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Margin-eligible company',
                'verbose_name_plural': 'Margin-eligible companies',
                'db_table': 'margin_eligible_companies',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['is_eligible', 'symbol'], name='margin_elig_is_elig_4f9b4e_idx')],
            },
        ),
    ]
