# Generated by Django 6.0.5 on 2026-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0013_margineligiblecompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundaFundamentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('security_name', models.CharField(blank=True, default='', max_length=255)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('period', models.CharField(help_text="e.g. '2024/25 Q4'", max_length=20)),
                ('fiscal_year_ad', models.CharField(blank=True, default='', max_length=10)),
                ('quarter', models.PositiveSmallIntegerField(default=0)),
                ('ks', models.JSONField(default=dict, help_text='Canonical keystats: eps, pe, roe, …')),
                ('trend', models.JSONField(default=list, help_text='Annual revenue / net-income points')),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Full statements payload')),
                ('source', models.CharField(default='funda.aurasrp.com.np', max_length=100)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
