# Generated by Django 6.0.5 on 2026-07-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0014_fundafundamentalsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundafundamentalsnapshot',
            name='fs_written',
            field=models.PositiveSmallIntegerField(default=0, help_text='KeyStats line items pushed into FinancialStatement on last sync'),
        ),
    ]
