# Generated by Django 6.0.5 on 2026-07-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0015_fundafundamentalsnapshot_fs_written'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepseMarketCapDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True, unique=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('sensitive_market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('float_market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('sensitive_float_market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('total_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('total_traded_shares', models.BigIntegerField(blank=True, null=True)),
                ('total_transactions', models.BigIntegerField(blank=True, null=True)),
                ('total_scrips_traded', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Nepse market cap (daily)',
                'db_table': 'nepse_market_cap_daily',
                'ordering': ['-business_date'],
            },
        ),
    ]
