# Generated by Django 6.0.5 on 2026-08-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0016_nepsemarketcapdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text='ShareSansar row id', unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('fiscal_year', models.CharField(db_index=True, help_text='BS, e.g. 2081/2082', max_length=20)),
                ('bonus_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cash_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('announcement_date', models.DateField(blank=True, db_index=True, null=True)),
                ('bookclose_date', models.DateField(blank=True, null=True)),
                ('bookclose_status', models.CharField(blank=True, default='', max_length=40)),
                ('distribution_date', models.DateField(blank=True, null=True)),
                ('bonus_listing_date', models.DateField(blank=True, null=True)),
                ('ltp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_as_of', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proposed_dividends',
                'ordering': ['-announcement_date', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'fiscal_year'], name='proposed_di_symbol_c49ad9_idx'), models.Index(fields=['fiscal_year', '-announcement_date'], name='proposed_di_fiscal__dbaa6f_idx')],
            },
        ),
    ]
