# Generated by Django 6.0.5 on 2026-08-10 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0017_proposeddividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('holdings_count', models.PositiveIntegerField(default=0)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('sync', 'EOD sync'), ('ledger', 'Ledger reconstruction')], db_index=True, default='sync', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core_analysis.portfolio')),
            ],
            options={
                'db_table': 'portfolio_snapshot',
                'ordering': ['-business_date'],
                'indexes': [models.Index(fields=['portfolio', 'business_date'], name='portfolio_s_portfol_b56806_idx')],
                'unique_together': {('portfolio', 'business_date')},
            },
        ),
    ]
