# Generated by Django 6.0.5 on 2026-08-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0018_portfoliosnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('nav_period', models.CharField(help_text="Nepali month as published, e.g. 'Asadh 2083'", max_length=32)),
                ('fund_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('fund_type', models.CharField(blank=True, default='', max_length=2)),
                ('fund_size', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('maturity_period', models.CharField(blank=True, default='', max_length=40)),
                ('nav_monthly', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('nav_weekly', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('nav_weekly_date', models.DateField(blank=True, null=True)),
                ('nav_daily', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('nav_daily_date', models.DateField(blank=True, null=True)),
                ('refund_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('market_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market_close_date', models.DateField(blank=True, null=True)),
                ('premium_discount_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mutual_fund_nav',
                'indexes': [models.Index(fields=['symbol', '-synced_at'], name='mutual_fund_symbol_c86e16_idx')],
                'unique_together': {('symbol', 'nav_period')},
            },
        ),
    ]
