# Generated by Django 6.0.5 on 2026-08-24 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0019_mutualfundnav'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('period', models.CharField(db_index=True, help_text="Canonical Nepali month, e.g. 'Ashadh 2083'", max_length=32)),
                ('fund_name', models.CharField(blank=True, default='', max_length=255)),
                ('nav_monthly', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('nav_daily', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ltp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('equity_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fixed_income_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('other_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('source_name', models.CharField(blank=True, default='', help_text='Uploaded file this came from', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mutual_fund_portfolio',
                'indexes': [models.Index(fields=['period', 'symbol'], name='mutual_fund_period_cf10d3_idx')],
                'unique_together': {('symbol', 'period')},
            },
        ),
        migrations.CreateModel(
            name='MutualFundHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('sector', models.CharField(blank=True, default='', help_text='As printed in the report', max_length=80)),
                ('kitta', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core_analysis.mutualfundportfolio')),
            ],
            options={
                'db_table': 'mutual_fund_holding',
                'indexes': [models.Index(fields=['script'], name='mutual_fund_script_fbb97d_idx')],
                'unique_together': {('portfolio', 'script')},
            },
        ),
    ]
