# Generated by Django 6.0.5 on 2026-08-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0020_mutualfundportfolio_mutualfundholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundportfolio',
            name='net_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
