# Generated by Django 6.0.5 on 2026-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0021_mutualfundportfolio_net_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('fund_name', models.CharField(blank=True, default='', max_length=255)),
                ('amc', models.CharField(blank=True, default='', help_text='Asset management company', max_length=255)),
                ('amc_member', models.CharField(blank=True, default='', max_length=255)),
                ('fund_size', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('maturity_period', models.CharField(blank=True, default='', max_length=64)),
                ('daily_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('daily_nav_date', models.DateField(blank=True, null=True)),
                ('monthly_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('monthly_nav_period', models.CharField(blank=True, default='', max_length=32)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mutual_fund_profile',
                'ordering': ['symbol'],
            },
        ),
    ]
