# Generated by Django 6.0.5 on 2026-08-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0022_mutualfundprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundholding',
            name='weight_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
