# Generated by Django 6.0.5 on 2026-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0023_mutualfundholding_weight_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundStatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('period', models.CharField(db_index=True, help_text='Canonical Nepali month', max_length=32)),
                ('fs_type', models.CharField(max_length=4)),
                ('item_name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('nav_date', models.DateField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'mutual_fund_statement_item',
                'ordering': ['fs_type', 'position', 'item_name'],
                'indexes': [models.Index(fields=['symbol', 'period', 'fs_type'], name='mutual_fund_symbol_0b3c26_idx')],
                'unique_together': {('symbol', 'period', 'fs_type', 'item_name')},
            },
        ),
    ]
