# Generated by Django 6.0.5 on 2026-09-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0024_mutualfundstatementitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeInsuranceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('fiscal_year_ad', models.CharField(db_index=True, help_text='e.g. 2025/26', max_length=10)),
                ('quarter', models.PositiveSmallIntegerField(help_text='1-4')),
                ('policies_issued', models.BigIntegerField(blank=True, help_text='Total no. of policies issued during the year', null=True)),
                ('gross_claim_outstanding', models.DecimalField(blank=True, decimal_places=2, help_text='Rs, as printed', max_digits=20, null=True)),
                ('declared_bonus_rate', models.CharField(blank=True, default='', help_text="As printed, e.g. 'Rs. 55 - Rs. 85 Per Thousand'", max_length=80)),
                ('interim_bonus_rate', models.CharField(blank=True, default='', max_length=80)),
                ('policyholders_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investment_at_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('life_insurance_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unearned_premium_reserve', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('solvency_margin_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source_note', models.CharField(blank=True, default='', help_text="Where the figures came from, e.g. 'Q4 2082/83 report p.7'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'life_insurance_indicators',
                'ordering': ['-fiscal_year_ad', '-quarter', 'ticker'],
                'unique_together': {('ticker', 'fiscal_year_ad', 'quarter')},
            },
        ),
    ]
