# Generated by Django 6.0.5 on 2026-09-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0025_lifeinsuranceindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeinsuranceindicator',
            name='sector',
            field=models.CharField(db_index=True, default='Life Insurance', max_length=40),
        ),
    ]
