# Generated by Django 6.0.5 on 2026-09-07 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0026_lifeinsuranceindicator_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Bond ticker, e.g. NBLD87', max_length=30, unique=True)),
                ('security_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('issuer_note', models.CharField(blank=True, default='', max_length=255)),
                ('coupon_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('maturity_date', models.DateField(blank=True, db_index=True, null=True)),
                ('years_to_maturity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('issue_size', models.DecimalField(blank=True, decimal_places=2, help_text='Total face value of the issue, Rs', max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_quality', models.CharField(blank=True, default='', help_text='Adequate / Stale - N days / Thin / No trade', max_length=60)),
                ('ytm_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('benchmark_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('spread_bp', models.IntegerField(blank=True, null=True)),
                ('fair_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valuation', models.CharField(blank=True, db_index=True, default='', help_text='Undervalued / Fairly valued / Overvalued / Not traded', max_length=30)),
                ('macaulay_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('modified_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('valuation_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(blank=True, db_column='issuer_symbol', help_text='Equity symbol of the issuing company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonds', to='core_analysis.companyprofile')),
            ],
            options={
                'db_table': 'bond_valuations',
                'ordering': ['maturity_date', 'symbol'],
                'indexes': [models.Index(fields=['issuer', 'maturity_date'], name='bond_valuat_issuer__df349f_idx')],
            },
        ),
    ]
