# Generated by Django 6.0.5 on 2026-09-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_analysis', '0027_bondvaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDepthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(help_text='Row id on the feed host', unique=True)),
                ('business_date', models.DateField(db_index=True)),
                ('captured_at', models.DateTimeField(db_index=True, help_text='Capture wall-clock time (feed date + time)')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('board', models.CharField(blank=True, default='1', max_length=10)),
                ('total_bids', models.BigIntegerField(default=0)),
                ('total_asks', models.BigIntegerField(default=0)),
                ('depth', models.JSONField(default=dict, help_text='{"bids": [...], "asks": [...]} raw top-5 book')),
                ('best_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('best_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bid_qty_top5', models.BigIntegerField(default=0)),
                ('ask_qty_top5', models.BigIntegerField(default=0)),
                ('bid_splits_top5', models.IntegerField(default=0)),
                ('ask_splits_top5', models.IntegerField(default=0)),
                ('aon_side', models.CharField(blank=True, default='', max_length=10)),
                ('aon_status', models.CharField(blank=True, default='', max_length=30)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_depth_snapshots',
                'ordering': ['symbol', 'captured_at'],
                'indexes': [models.Index(fields=['symbol', 'captured_at'], name='market_dept_symbol_907b4e_idx'), models.Index(fields=['business_date', 'symbol'], name='market_dept_busines_a8d2f1_idx')],
            },
        ),
    ]
